### ISSUE TITLE
country_list

### ISSUE THREAD

**Issue by TitouanRobert** [rte-antares-rpackage/fbClust#7]
Ajouter un contrôle qui donne un warning:
country_list = list(NL = c("BE", "DE", "FR", "AT", "UK"))
UK not found in country_list.

**Comment by TitouanRobert** [comment]
Erreur : 

country_list = list(AT = c("BE", "DE", "FR"))
DD <- clusterTypicalDaysForOneClass(
  dates = dates, PLAN = PLAN, VERT = NULL, maxDomainSize = 15000,
  country_list = country_list,
  nbCluster = nbcluster,report = F, hourWeight = hourWeight, id_start = id_start)

 Error in .ctrlCountryList(country_list = country_list, PLAN = PLAN) : 
  country_list does not contain all the ptdf in PLAN 

Ajour d'un autre contrôle qui donne une erreure : 
country_list = list(UK= c("BE", "DE", "FR"))

-> UK not in ptdf name

**Comment by JulienBretteville** [comment]
Pour le premier message, tu trouves que l'erreur n'est pas normale ?
Normalement tu dois avoir NL dans country_list (à moins que tu l'aies pas dans ton data.frame PLAN initial bien sûr), le problème doit venir de là non ?

**Comment by TitouanRobert** [comment]
Ok, que penses-tu de le remplacer par un warning (au cas ou jeu de PTDF arrive avec certaines colonnes déjà différenciées)?

**Comment by JulienBretteville** [comment]
Je peux le faire si tu y tiens mais ce serait étonnant qu'il y ait certaines colonnes différenciées mais pas toutes non ?
